'use client';
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  import { motion } from 'framer-motion';
                                                                                                                                                                                                                                                                  import { useLanguage } from '@/lib/i18n/LanguageContext';
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  export function HomeLangToggle() {
                                                                                                                                                                                                                                                                    const { language, setLanguage } = useLanguage();
                                                                                                                                                                                                                                                                      const isBangla = language === 'bn';
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                            <motion.div
                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, y: -10 }}
                                                                                                                                                                                                                                                                                        animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                              transition={{ delay: 0.8, duration: 0.4 }}
                                                                                                                                                                                                                                                                                                    className="inline-flex items-center rounded-full p-[3px]"
                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                  background: 'linear-gradient(135deg, rgba(212,175,55,0.3) 0%, rgba(212,175,55,0.1) 100%)',
                                                                                                                                                                                                                                                                                                                          border: '1.5px solid rgba(212,175,55,0.5)',
                                                                                                                                                                                                                                                                                                                                  backdropFilter: 'blur(12px)',
                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                          onClick={() => setLanguage('en')}
                                                                                                                                                                                                                                                                                                                                                                  aria-label="Switch to English"
                                                                                                                                                                                                                                                                                                                                                                          className="relative px-4 py-1.5 rounded-full text-sm font-bold transition-all duration-300 cursor-pointer focus:outline-none"
                                                                                                                                                                                                                                                                                                                                                                                  style={{ minWidth: 52 }}
                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                {!isBangla && (
                                                                                                                                                                                                                                                                                                                                                                                                          <motion.span
                                                                                                                                                                                                                                                                                                                                                                                                                      layoutId="home-lang-active"
                                                                                                                                                                                                                                                                                                                                                                                                                                  className="absolute inset-0 rounded-full bg-yellow-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                              transition={{ type: 'spring', stiffness: 500, damping: 35 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className={"relative z-10 transition-colors duration-200 " + (!isBangla ? 'text-gray-900' : 'text-white/70')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ fontFamily: 'system-ui, sans-serif' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setLanguage('bn')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                aria-label={"\\u09ac\\u09be\\u0982\\u09b2\\u09be\\u09df \\u09aa\\u09b0\\u09bf\\u09ac\\u09b0\\u09cd\\u09a4\\u09a8 \\u0995\\u09b0\\u09c1\\u09a8"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="relative px-4 py-1.5 rounded-full text-sm font-bold transition-all duration-300 cursor-pointer focus:outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ minWidth: 52 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isBangla && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <motion.span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    layoutId="home-lang-active"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="absolute inset-0 rounded-full bg-yellow-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition={{ type: 'spring', stiffness: 500, damping: 35 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className={"relative z-10 transition-colors duration-200 " + (isBangla ? 'text-gray-900' : 'text-white/70')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ fontFamily: 'serif' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {"\\u09ac\\u09be\\u0982"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }